### ISSUE TITLE
Error: Build Dependencies - Xubuntu Kernel 4.20.7

### ISSUE THREAD

**Issue by FredC88** [coolshou/rtl8814au#4]
dpkg-buildpackage -b
dpkg-buildpackage: info: source package rtl8814au
dpkg-buildpackage: info: source version 4.3.21.1-24835.20190115
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by jimmy <jimmy@jimmy-alpha>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build driver
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9) dh-modaliases
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

Thank you very much!!

**Comment by coolshou** [comment]
try install require package first
sudo apt install  debhelper dpkg-dev dkms dh-modaliases

**Comment by FredC88** [comment]
Thanks for the quick help!!! :+1:  But...it still doesn't work, error message as below(Kernel 5.0-rc6):

dpkg-buildpackage: info: source package rtl8814au
dpkg-buildpackage: info: source version 4.3.21.1-24835.20190115
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by jimmy <jimmy@jimmy-alpha>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build driver
 fakeroot debian/rules clean
dh "clean" --with dkms,modaliases
   dh_auto_clean
	make -j1 clean
make[1]: Entering directory '/home/joana/Desktop/Wifi_Driver/Coolshou/rtl8814au/driver'
cd hal/phydm/ ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal/phydm/ ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd hal/led ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd hal ; rm -fr */*/*.mod.c */*/*.mod */*/*.o */*/.*.cmd */*/*.ko
cd hal ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core/efuse ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep/linux ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd platform ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
rm -fr Module.symvers ; rm -fr Module.markers ; rm -fr modules.order
rm -fr *.mod.c *.mod *.o .*.cmd *.ko *~
rm -fr .tmp_versions
make[1]: Leaving directory '/home/joana/Desktop/Wifi_Driver/Coolshou/rtl8814au/driver'
   dh_clean
 debian/rules build
dh "build" --with dkms,modaliases
   dh_update_autotools_config
 fakeroot debian/rules binary
dh "binary" --with dkms,modaliases
   dh_testroot
   dh_prep
   debian/rules override_dh_install
make[1]: Entering directory '/home/joana/Desktop/Wifi_Driver/Coolshou/rtl8814au/driver'
dh_install core hal include Kconfig Makefile os_dep platform usr/src/rtl8814au-4.3.21.1/
find debian/rtl8814au-dkms/usr/src/rtl8814au-4.3.21.1 -type f -exec chmod 644 {} \;
make[1]: Leaving directory '/home/joana/Desktop/Wifi_Driver/Coolshou/rtl8814au/driver'
   dh_modaliases
   dh_installdocs
   dh_installchangelogs
   debian/rules override_dh_dkms
make[1]: Entering directory '/home/joana/Desktop/Wifi_Driver/Coolshou/rtl8814au/driver'
dh_dkms -V 4.3.21.1
make[1]: Leaving directory '/home/joana/Desktop/Wifi_Driver/Coolshou/rtl8814au/driver'
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_installdeb
   dh_gencontrol
dpkg-gencontrol: warning: package rtl8814au-dkms: unknown substitution variable ${modaliases}
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'rtl8814au-dkms' in '../rtl8814au-dkms_4.3.21.1-24835.20190115_all.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../rtl8814au_4.3.21.1-24835.20190115_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build driver
dpkg-buildpackage: info: binary-only upload (no source included)
 signfile rtl8814au_4.3.21.1-24835.20190115_amd64.buildinfo
gpg: keybox '/home/joana/.gnupg/pubring.kbx' created
gpg: skipped "jimmy <jimmy@jimmy-alpha>": No secret key
gpg: dpkg-sign.C5z5tcqa/rtl8814au_4.3.21.1-24835.20190115_amd64.buildinfo: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .buildinfo file

**Comment by coolshou** [comment]
The package did build successful. the error just mean signature error.
you can use following cmd to install the driver
`dpkg -i ../rtl8814au-dkms_4.3.21.1-24835.20190115_all.deb `
or you can build the package with following cmd to skip sign error
`dpkg-buildpackage -b --no-sign`

**Comment by FredC88** [comment]
Thank you very much for your help & support man!! :+1:  However, I come to the last stage and find out - Kernel 5.0-rc6 is not supported yet... :(

14au-dkms_4.3.21.1-24835.20190212_all.deb
Selecting previously unselected package rtl8814au-dkms.
(Reading database ... 220602 files and directories currently installed.)
Preparing to unpack rtl8814au-dkms_4.3.21.1-24835.20190212_all.deb ...
Unpacking rtl8814au-dkms (4.3.21.1-24835.20190212) ...
Setting up rtl8814au-dkms (4.3.21.1-24835.20190212) ...
Loading new rtl8814au-4.3.21.1 DKMS files...
Building for 5.0.0-050000rc6-generic
Building initial module for 5.0.0-050000rc6-generic
ERROR (dkms apport): kernel package linux-headers-5.0.0-050000rc6-generic is not supported
Error! Bad return status for module build on kernel: 5.0.0-050000rc6-generic (x86_64)
Consult /var/lib/dkms/rtl8814au/4.3.21.1/build/make.log for more information.

  CC [M]  /var/lib/dkms/rtl8814au/4.3.21.1/build/os_dep/linux/rtw_android.o
/var/lib/dkms/rtl8814au/4.3.21.1/build/os_dep/linux/rtw_android.c: In function ‘rtw_android_priv_cmd’:
/var/lib/dkms/rtl8814au/4.3.21.1/build/os_dep/linux/rtw_android.c:615:62: error: macro "access_ok" passed 3 arguments, but takes just 2
  if (!access_ok(VERIFY_READ, priv_cmd.buf, priv_cmd.total_len)){

Make Error Log:
=============
                                                              ^
/var/lib/dkms/rtl8814au/4.3.21.1/build/os_dep/linux/rtw_android.c:615:7: error: ‘access_ok’ undeclared (first use in this function)
  if (!access_ok(VERIFY_READ, priv_cmd.buf, priv_cmd.total_len)){
       ^~~~~~~~~
/var/lib/dkms/rtl8814au/4.3.21.1/build/os_dep/linux/rtw_android.c:615:7: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:276: recipe for target '/var/lib/dkms/rtl8814au/4.3.21.1/build/os_dep/linux/rtw_android.o' failed
make[2]: *** [/var/lib/dkms/rtl8814au/4.3.21.1/build/os_dep/linux/rtw_android.o] Error 1
Makefile:1553: recipe for target '_module_/var/lib/dkms/rtl8814au/4.3.21.1/build' failed
make[1]: *** [_module_/var/lib/dkms/rtl8814au/4.3.21.1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-050000rc5-generic'
Makefile:1730: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by coolshou** [comment]
I do not have kernel 5.0 but make some update according other's suggest
try pull the last code and build the driver first(check if there are any other errors)
`git pull `
`make`

**Comment by FredC88** [comment]
You are the Greatest man!! :+1: :+1: :+1: :1st_place_medal:  New ver. solved all the problems!!! Tested Ok on Kernel 5.0-rc6!!

Thank you again coolshou!! Appreciated for all your contributions and help!!
